-- Script estensione schema DB_INV con REPARTI, AREE
-- Esecuzione: mysql -u root -p DB_INV < extend-schema.sql

USE DB_INV;

-- Tabella REPARTI: anagrafica reparti/negozi
CREATE TABLE IF NOT EXISTS REPARTI (
  ID_REP       INT           NOT NULL PRIMARY KEY,
  DESCRIZIONE  VARCHAR(100)  NOT NULL,
  CREATED_AT   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabella AREE: anagrafica aree di inventario
CREATE TABLE IF NOT EXISTS AREE (
  ID_AREA      INT           NOT NULL PRIMARY KEY,
  DESCRIZIONE  VARCHAR(100)  NOT NULL,
  CREATED_AT   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Nota: STAMPANTI mantiene struttura semplice (solo IP, CODA_CUPS)
-- Non sono richiesti metadati o associazioni REPARTI

-- Inserimenti REPARTI
INSERT INTO REPARTI (ID_REP, DESCRIZIONE) VALUES
(1,  'HABITAMI LAMEZIA'),
(2,  'PRONTO HOBBY LAMEZIA'),
(5,  'HABITAMI MAIDA'),
(11, 'SHOWROOM LAMEZIA'),
(15, 'SHOWROOM MAIDA'),
(33, 'PRONTO HOME MAIDA'),
(35, 'PRONTO HOBBY MAIDA'),
(36, 'PRONTO HOBBY SQUILLACE'),
(37, 'PRONTO HOBBY AMANTEA'),
(39, 'PRONTO HOBBY CATANZARO BARONE'),
(49, 'PRONTO HOBBY MAGNA GRECIA'),
(65, 'PRONTO HOBBY RENDE')
ON DUPLICATE KEY UPDATE DESCRIZIONE = VALUES(DESCRIZIONE);

-- Inserimenti AREE
INSERT INTO AREE (ID_AREA, DESCRIZIONE) VALUES
(-1, 'NON ASSEGNATA'),
(1,  'GARDEN'),
(2,  'CASA'),
(3,  'VERNICI'),
(4,  'TAGLIO LEGNO'),
(5,  'FERRAMENTA'),
(6,  'ILLUMINAZIONE'),
(7,  'ARREDO BAGNO'),
(8,  'JOLLY'),
(9,  'ALTRE AREE')
ON DUPLICATE KEY UPDATE DESCRIZIONE = VALUES(DESCRIZIONE);

-- Aggiorna STAMPANTI con ID_REP = 5 (HABITAMI MAIDA)
UPDATE STAMPANTI SET ID_REP = 5 WHERE IP = '172.16.8.248';

-- Verifica
SELECT 'REPARTI' as `Table`, COUNT(*) as Count FROM REPARTI
UNION ALL
SELECT 'AREE', COUNT(*) FROM AREE
UNION ALL
SELECT 'STAMPANTI', COUNT(*) FROM STAMPANTI;

-- Mostra dati inseriti
SELECT '--- REPARTI ---' as info;
SELECT * FROM REPARTI ORDER BY ID_REP;

SELECT '--- AREE ---' as info;
SELECT * FROM AREE ORDER BY ID_AREA;

SELECT '--- STAMPANTI ---' as info;
SELECT IP, CODA_CUPS, ID_REP, NOTE FROM STAMPANTI;
