-- Schema inventario per DB_INV
-- Creazione database
CREATE DATABASE IF NOT EXISTS DB_INV 
  CHARACTER SET utf8mb4 
  COLLATE utf8mb4_0900_ai_ci;

USE DB_INV;

-- Tabella MARKER: identifica i tipi di marker in INVC
CREATE TABLE MARKER (
  PRECODICE  CHAR(3)  NOT NULL,
  CODICE_ART CHAR(6) NOT NULL,
  PRIMARY KEY (PRECODICE, CODICE_ART)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO MARKER (PRECODICE, CODICE_ART) VALUES
('ZZZ', 'AREA'),
('ZZZ', 'STAMPA');

-- Tabella CONTEGGI: mirror di INVC (DB2) + gestione
CREATE TABLE CONTEGGI (
  ID_CONTEGGIO     INT           NOT NULL AUTO_INCREMENT,
  REPARTO          SMALLINT      NOT NULL,
  NUMERO_INV       INT           NOT NULL,
  PRECODICE        CHAR(3)       NOT NULL,
  CODICE_ART       CHAR(20)      NOT NULL,
  POSIZIONE        CHAR(8)       NOT NULL,
  NUMERO_CONTA     SMALLINT      NOT NULL,
  PROG             SMALLINT      NOT NULL,
  QTA_CONTEGGIATA  DECIMAL(11,3)     NULL,
  OPER_CREAZ       CHAR(6)           NULL,
  TS_CREAZIONE     DATETIME          NULL,
  CODICE_OPERATORE VARCHAR(10)       NULL,
  ID_AREA          INT           NOT NULL DEFAULT -1,
  STAMPATO         TINYINT(1)    NOT NULL DEFAULT 0,
  DATA_IMPORT      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_CONTEGGIO),
  UNIQUE KEY uk_conteggi_inv
    (REPARTO, NUMERO_INV, PRECODICE, CODICE_ART, POSIZIONE, NUMERO_CONTA, PROG),
  INDEX idx_operatore (CODICE_OPERATORE),
  INDEX idx_area (ID_AREA),
  INDEX idx_stampato (STAMPATO),
  INDEX idx_ts_creazione (TS_CREAZIONE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabella CONF_OPERATORE: configurazione corrente operatore per reparto/inventario
CREATE TABLE CONF_OPERATORE (
  ID_CONF        INT           NOT NULL AUTO_INCREMENT,
  CODICE         VARCHAR(10)   NOT NULL,
  NOME           CHAR(30)          NULL,
  ID_REP         INT           NOT NULL,
  ID_INVENTARIO  INT           NOT NULL,
  ID_AREA        INT           NOT NULL DEFAULT -1,
  IP_STAMPANTE   CHAR(15)      NOT NULL,
  CREATED_AT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_CONF),
  UNIQUE KEY uq_conf (CODICE, ID_REP, ID_INVENTARIO),
  INDEX idx_operatore (CODICE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabella STAMPANTI: mappatura IP → coda CUPS
CREATE TABLE STAMPANTI (
  IP        CHAR(15)     NOT NULL,
  CODA_CUPS VARCHAR(50)  NOT NULL,
  PRIMARY KEY (IP),
  UNIQUE KEY uq_coda (CODA_CUPS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabella IMPORT_LOG: traccia esecuzioni import
CREATE TABLE IMPORT_LOG (
  ID_LOG         INT          NOT NULL AUTO_INCREMENT,
  EXEC_START     DATETIME     NOT NULL,
  EXEC_END       DATETIME         NULL,
  ROWS_PROCESSED INT          NOT NULL DEFAULT 0,
  ROWS_INSERTED  INT          NOT NULL DEFAULT 0,
  ROWS_UPDATED   INT          NOT NULL DEFAULT 0,
  MARKERS_FOUND  INT          NOT NULL DEFAULT 0,
  STATUS         ENUM('RUNNING','SUCCESS','ERROR') NOT NULL DEFAULT 'RUNNING',
  ERROR_MSG      TEXT             NULL,
  PRIMARY KEY (ID_LOG),
  INDEX idx_exec_start (EXEC_START)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Creazione utente MySQL per l'applicazione
-- NOTA: Eseguire manualmente come root se necessario
-- CREATE USER 'DB_INV'@'localhost' IDENTIFIED BY 'DB_INV';
-- GRANT ALL PRIVILEGES ON DB_INV.* TO 'DB_INV'@'localhost';
-- FLUSH PRIVILEGES;
